POST http://localhost:3000/register
Content-Type: application/json


{
  "username": "rajkumar@4",
  "name": "Adam Richard",
  "password": "raj",
  "gender": "male",
  "location": "Detroit"
}

###
POST http://localhost:3000/login
Content-Type:application/json

{
  "username": "rajkumar@2",
  "password": "rajkumar@2"
}


###
PUT http://localhost:3000/change-password
Content-Type:application/json

{
  "username": "rajkumar@2",
  "oldPassword": "rajkumar@2",
  "newPassword": "rajkumar@1"
}



###
GET http://localhost:3000/todo/ 
